"""empty message

Revision ID: c6ec761271fc
Revises: d915f90bdc79
Create Date: 2022-07-06 17:13:14.565044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ec761271fc'
down_revision = 'd915f90bdc79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
