"""empty message

Revision ID: d915f90bdc79
Revises: a8b93ff65f81
Create Date: 2022-07-05 00:44:24.287730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd915f90bdc79'
down_revision = 'a8b93ff65f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('climate', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planet_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('birth_year', table_name='character')
    op.drop_index('birth_year_2', table_name='character')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('birth_year_2', 'character', ['birth_year'], unique=False)
    op.create_index('birth_year', 'character', ['birth_year'], unique=False)
    op.drop_table('planet_favorite')
    op.drop_table('planet')
    # ### end Alembic commands ###
